### ISSUE TITLE
Cant open Local config

### ISSUE THREAD

**Issue by ChristofferThinggaard** [SKAARHOJ/skaarhoj-updater-releases#8] opened 2020-02-04 13:27 UTC
Trying to open local config gave me an error.
something about com port ? 

Background Issue: 
      
```
Error: Opening COM3: Access denied
```

---

SKAARHOJUpdaterBeta 0.9.20
Electron 6.1.4
win32 10.0.18362
Locale: da

**Comment by ChristofferThinggaard** [comment] 2020-02-04 13:58
Just happened again.

Here is the text from the popup

Unhandled Promise Rejection
Error: Opening COM3: Access denied

**Comment by s00500** [comment] 2020-02-10 10:37
Duplicate of #7 , closing

**Closed as completed by s00500** 2020-02-10 10:37 UTC
