### ISSUE TITLE
Issue with GPIO module

### ISSUE THREAD

**Issue by alexgmoonFTS** [SKAARHOJ/skaarhoj-updater-releases#4] opened 2020-01-17 16:50 UTC
Background Issue: 
      
```
Error: Object has been destroyed
    at BrowserWindow.setProgressBar (<anonymous>)
    at Bossa.<anonymous> (/Applications/SKAARHOJUpdaterBeta.app/Contents/Resources/app.asar/background.js:37:322050)
    at Bossa.emit (events.js:205:15)
```

---

SKAARHOJUpdaterBeta 0.9.19
Electron 6.1.4
darwin 18.7.0
Locale: en-US

**Comment by s00500** [comment] 2020-01-17 17:09
Hi Alex, thanks for reporting this issue,
Did you close the window at any point ? or can you post the logfile ? It would be interesting how this problem can be reproduced reliably?

Are you on windows ? or some other OS ?

Greetings

**Comment by s00500** [comment] 2020-01-17 17:10
Duplicate of #3 in different environment

**Comment by alexgmoonFTS** [comment] 2020-01-17 17:45
I closed the window, and restarted the software and it worked correctly.

I am on OSX 10.14.6
*Alex G. Moon, CTS-D*

Director of Engineering and Service, Force Technology Solutions

O: 317.586.2844 | M: *317.919.5173* | www.forcetechsolutions.com |
6097 W 400 N STE C. GREENFIELD, IN 46140-6201

[image: https://s3.amazonaws.com/images.wisestamp.com/icons_32/facebook.png]
<http://www.facebook.com/forcetechsolutions/> [image:
https://s3.amazonaws.com/images.wisestamp.com/icons_32/linkedin.png]
<http://www.linkedin.com/in/alex-moon-2118592b>


CONFIDENTIALITY NOTICE:
This email message sent by AGMoon@force.tech or AGMoon
@forcetechsolutions.com and any accompanying data or files
are confidential and may contain privileged information intended only for
the named recipient(s). If you are not the intended recipient(s), you are
hereby notified that the dissemination, distribution, and or copying of
this message is strictly prohibited. If you receive this message in error,
or are not the named recipient(s), please notify the sender at the email
address above, delete this email from your computer, and destroy any copies
in any form immediately. Receipt by anyone other than the named
recipient(s) is not a waiver of any attorney-client, work product, or other
applicable privilege.

**Comment by s00500** [comment] 2020-01-24 09:41
v0.9.20 should fix the issue completely

**Comment by s00500** [comment] 2020-02-10 10:39
@alexgmoonFTS Can you confirm this is fixed? Otherwise just reopen this issue, Thanks

**Closed as completed** 2020-02-10 10:43 UTC
Labels: Plattform: macOS 💻, Type: Bug
