### ISSUE TITLE
Check For Updates Error

### ISSUE THREAD

**Issue by MattGrayYes** [SKAARHOJ/skaarhoj-updater-releases#6] opened 2020-01-23 17:57 UTC
While checking for updates for Rack Fusion Live, popup error keeps appearing:

Background Issue: 
      
```
Error: Object has been destroyed
    at BrowserWindow.setProgressBar (<anonymous>)
    at Bossa.<anonymous> (/Applications/SKAARHOJUpdaterBeta.app/Contents/Resources/app.asar/background.js:37:322050)
    at Bossa.emit (events.js:205:15)
```

---

SKAARHOJUpdaterBeta 0.9.19
Electron 6.1.4
darwin 18.7.0
Locale: en-GB

**Comment by MattGrayYes** [comment] 2020-01-23 17:57
<img width="702" alt="Screenshot 2020-01-23 at 17 57 40" src="https://user-images.githubusercontent.com/804029/73010201-deb12300-3e09-11ea-948d-3cebab5532af.png">

**Comment by s00500** [comment] 2020-01-24 08:27
Hey, thanks for reporting, we are looking into it already
duplicate of #4

**Comment by s00500** [comment] 2020-01-24 09:48
v0.9.20 should fix this issue
Knew Tom Scotts youtube for a long while, now I know yours 👍
Greetings

**Comment by s00500** [comment] 2020-02-10 10:38
@MattGrayYes Can you confirm this issue is fixed ? Otherwise just reopen here

**Closed as completed by s00500** 2020-02-10 10:38 UTC
Labels: Plattform: macOS 💻, Type: Bug

**Comment by MattGrayYes** [comment] 2020-02-10 13:43
Yep that’s fixed it for me!
Thanks.
